//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dropthings.DataAccess.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=localhost;Initial Catalog=Dashboard;User ID=sa2")]
        public string DashboardConnectionString {
            get {
                return ((string)(this["DashboardConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=E:\\Development\\OutSource\\Dropthings\\tru" +
            "nk\\Dropthings\\App_Data\\dropthings.mdf;Integrated Security=True;User Instance=Tru" +
            "e")]
        public string dropthingsConnectionString {
            get {
                return ((string)(this["dropthingsConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VISTA64;Initial Catalog=Dropthings;User ID=dropthings;Password=dropth" +
            "ings")]
        public string DropthingsConnectionString1 {
            get {
                return ((string)(this["DropthingsConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=VISTA64;Initial Catalog=Dropthings;User ID=dropthings")]
        public string DropthingsConnectionString2 {
            get {
                return ((string)(this["DropthingsConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=E:\\Development\\Official\\OnSoftware\\Drop" +
            "things29Nov2008\\trunk\\Dropthings\\App_Data\\dropthings.mdf;Integrated Security=Tru" +
            "e;User Instance=True")]
        public string dropthingsConnectionString3 {
            get {
                return ((string)(this["dropthingsConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=C:\\Users\\dmildenberger\\Desktop\\dropthin" +
            "gs-24028\\trunk\\Dropthings\\App_Data\\dropthings.mdf;Integrated Security=True;User " +
            "Instance=True")]
        public string dropthingsConnectionString4 {
            get {
                return ((string)(this["dropthingsConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=E:\\Development\\OpenSource\\DT\\dropthings" +
            "\\src\\Dropthings\\App_Data\\dropthings.mdf;Integrated Security=True;User Instance=T" +
            "rue")]
        public string dropthingsConnectionString5 {
            get {
                return ((string)(this["dropthingsConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=E:\\Development\\OpenSource\\DT2\\dropthing" +
            "s\\src\\Dropthings\\App_Data\\dropthings.mdf;Integrated Security=True;User Instance=" +
            "True")]
        public string dropthingsConnectionString6 {
            get {
                return ((string)(this["dropthingsConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=.\\SQLEXPRESS;AttachDbFilename=\"F:\\Ilias Vai\\Dropthings\\trunk\\src\\Drop" +
            "things\\App_Data\\dropthings.mdf\";Integrated Security=True;User Instance=True")]
        public string dropthingsConnectionString7 {
            get {
                return ((string)(this["dropthingsConnectionString7"]));
            }
        }
    }
}
