//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40818.0
// 
namespace Dropthings.DiggSilverlight.DropthingsProxyService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DropthingsProxyService.ProxyAsyncSoap")]
    public interface ProxyAsyncSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetRss", ReplyAction="*")]
        System.IAsyncResult BeginGetRss(Dropthings.DiggSilverlight.DropthingsProxyService.GetRssRequest request, System.AsyncCallback callback, object asyncState);
        
        Dropthings.DiggSilverlight.DropthingsProxyService.GetRssResponse EndGetRss(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetString", ReplyAction="*")]
        System.IAsyncResult BeginGetString(Dropthings.DiggSilverlight.DropthingsProxyService.GetStringRequest request, System.AsyncCallback callback, object asyncState);
        
        Dropthings.DiggSilverlight.DropthingsProxyService.GetStringResponse EndGetString(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetXml", ReplyAction="*")]
        System.IAsyncResult BeginGetXml(Dropthings.DiggSilverlight.DropthingsProxyService.GetXmlRequest request, System.AsyncCallback callback, object asyncState);
        
        Dropthings.DiggSilverlight.DropthingsProxyService.GetXmlResponse EndGetXml(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRssRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRss", Namespace="http://tempuri.org/", Order=0)]
        public Dropthings.DiggSilverlight.DropthingsProxyService.GetRssRequestBody Body;
        
        public GetRssRequest() {
        }
        
        public GetRssRequest(Dropthings.DiggSilverlight.DropthingsProxyService.GetRssRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRssRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string url;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int count;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int cacheDuration;
        
        public GetRssRequestBody() {
        }
        
        public GetRssRequestBody(string url, int count, int cacheDuration) {
            this.url = url;
            this.count = count;
            this.cacheDuration = cacheDuration;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetRssResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetRssResponse", Namespace="http://tempuri.org/", Order=0)]
        public Dropthings.DiggSilverlight.DropthingsProxyService.GetRssResponseBody Body;
        
        public GetRssResponse() {
        }
        
        public GetRssResponse(Dropthings.DiggSilverlight.DropthingsProxyService.GetRssResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetRssResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public object GetRssResult;
        
        public GetRssResponseBody() {
        }
        
        public GetRssResponseBody(object GetRssResult) {
            this.GetRssResult = GetRssResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStringRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetString", Namespace="http://tempuri.org/", Order=0)]
        public Dropthings.DiggSilverlight.DropthingsProxyService.GetStringRequestBody Body;
        
        public GetStringRequest() {
        }
        
        public GetStringRequest(Dropthings.DiggSilverlight.DropthingsProxyService.GetStringRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStringRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string url;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int cacheDuration;
        
        public GetStringRequestBody() {
        }
        
        public GetStringRequestBody(string url, int cacheDuration) {
            this.url = url;
            this.cacheDuration = cacheDuration;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetStringResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetStringResponse", Namespace="http://tempuri.org/", Order=0)]
        public Dropthings.DiggSilverlight.DropthingsProxyService.GetStringResponseBody Body;
        
        public GetStringResponse() {
        }
        
        public GetStringResponse(Dropthings.DiggSilverlight.DropthingsProxyService.GetStringResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetStringResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetStringResult;
        
        public GetStringResponseBody() {
        }
        
        public GetStringResponseBody(string GetStringResult) {
            this.GetStringResult = GetStringResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXmlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXml", Namespace="http://tempuri.org/", Order=0)]
        public Dropthings.DiggSilverlight.DropthingsProxyService.GetXmlRequestBody Body;
        
        public GetXmlRequest() {
        }
        
        public GetXmlRequest(Dropthings.DiggSilverlight.DropthingsProxyService.GetXmlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetXmlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string url;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int cacheDuration;
        
        public GetXmlRequestBody() {
        }
        
        public GetXmlRequestBody(string url, int cacheDuration) {
            this.url = url;
            this.cacheDuration = cacheDuration;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetXmlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetXmlResponse", Namespace="http://tempuri.org/", Order=0)]
        public Dropthings.DiggSilverlight.DropthingsProxyService.GetXmlResponseBody Body;
        
        public GetXmlResponse() {
        }
        
        public GetXmlResponse(Dropthings.DiggSilverlight.DropthingsProxyService.GetXmlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetXmlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetXmlResult;
        
        public GetXmlResponseBody() {
        }
        
        public GetXmlResponseBody(string GetXmlResult) {
            this.GetXmlResult = GetXmlResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProxyAsyncSoapChannel : Dropthings.DiggSilverlight.DropthingsProxyService.ProxyAsyncSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetRssCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetRssCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public object Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((object)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GetXmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetXmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProxyAsyncSoapClient : System.ServiceModel.ClientBase<Dropthings.DiggSilverlight.DropthingsProxyService.ProxyAsyncSoap>, Dropthings.DiggSilverlight.DropthingsProxyService.ProxyAsyncSoap {
        
        private BeginOperationDelegate onBeginGetRssDelegate;
        
        private EndOperationDelegate onEndGetRssDelegate;
        
        private System.Threading.SendOrPostCallback onGetRssCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetStringDelegate;
        
        private EndOperationDelegate onEndGetStringDelegate;
        
        private System.Threading.SendOrPostCallback onGetStringCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetXmlDelegate;
        
        private EndOperationDelegate onEndGetXmlDelegate;
        
        private System.Threading.SendOrPostCallback onGetXmlCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public ProxyAsyncSoapClient() {
        }
        
        public ProxyAsyncSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProxyAsyncSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyAsyncSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProxyAsyncSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetRssCompletedEventArgs> GetRssCompleted;
        
        public event System.EventHandler<GetStringCompletedEventArgs> GetStringCompleted;
        
        public event System.EventHandler<GetXmlCompletedEventArgs> GetXmlCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Dropthings.DiggSilverlight.DropthingsProxyService.ProxyAsyncSoap.BeginGetRss(Dropthings.DiggSilverlight.DropthingsProxyService.GetRssRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetRss(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetRss(string url, int count, int cacheDuration, System.AsyncCallback callback, object asyncState) {
            Dropthings.DiggSilverlight.DropthingsProxyService.GetRssRequest inValue = new Dropthings.DiggSilverlight.DropthingsProxyService.GetRssRequest();
            inValue.Body = new Dropthings.DiggSilverlight.DropthingsProxyService.GetRssRequestBody();
            inValue.Body.url = url;
            inValue.Body.count = count;
            inValue.Body.cacheDuration = cacheDuration;
            return ((Dropthings.DiggSilverlight.DropthingsProxyService.ProxyAsyncSoap)(this)).BeginGetRss(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dropthings.DiggSilverlight.DropthingsProxyService.GetRssResponse Dropthings.DiggSilverlight.DropthingsProxyService.ProxyAsyncSoap.EndGetRss(System.IAsyncResult result) {
            return base.Channel.EndGetRss(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private object EndGetRss(System.IAsyncResult result) {
            Dropthings.DiggSilverlight.DropthingsProxyService.GetRssResponse retVal = ((Dropthings.DiggSilverlight.DropthingsProxyService.ProxyAsyncSoap)(this)).EndGetRss(result);
            return retVal.Body.GetRssResult;
        }
        
        private System.IAsyncResult OnBeginGetRss(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string url = ((string)(inValues[0]));
            int count = ((int)(inValues[1]));
            int cacheDuration = ((int)(inValues[2]));
            return this.BeginGetRss(url, count, cacheDuration, callback, asyncState);
        }
        
        private object[] OnEndGetRss(System.IAsyncResult result) {
            object retVal = this.EndGetRss(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetRssCompleted(object state) {
            if ((this.GetRssCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetRssCompleted(this, new GetRssCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetRssAsync(string url, int count, int cacheDuration) {
            this.GetRssAsync(url, count, cacheDuration, null);
        }
        
        public void GetRssAsync(string url, int count, int cacheDuration, object userState) {
            if ((this.onBeginGetRssDelegate == null)) {
                this.onBeginGetRssDelegate = new BeginOperationDelegate(this.OnBeginGetRss);
            }
            if ((this.onEndGetRssDelegate == null)) {
                this.onEndGetRssDelegate = new EndOperationDelegate(this.OnEndGetRss);
            }
            if ((this.onGetRssCompletedDelegate == null)) {
                this.onGetRssCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRssCompleted);
            }
            base.InvokeAsync(this.onBeginGetRssDelegate, new object[] {
                        url,
                        count,
                        cacheDuration}, this.onEndGetRssDelegate, this.onGetRssCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Dropthings.DiggSilverlight.DropthingsProxyService.ProxyAsyncSoap.BeginGetString(Dropthings.DiggSilverlight.DropthingsProxyService.GetStringRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetString(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetString(string url, int cacheDuration, System.AsyncCallback callback, object asyncState) {
            Dropthings.DiggSilverlight.DropthingsProxyService.GetStringRequest inValue = new Dropthings.DiggSilverlight.DropthingsProxyService.GetStringRequest();
            inValue.Body = new Dropthings.DiggSilverlight.DropthingsProxyService.GetStringRequestBody();
            inValue.Body.url = url;
            inValue.Body.cacheDuration = cacheDuration;
            return ((Dropthings.DiggSilverlight.DropthingsProxyService.ProxyAsyncSoap)(this)).BeginGetString(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dropthings.DiggSilverlight.DropthingsProxyService.GetStringResponse Dropthings.DiggSilverlight.DropthingsProxyService.ProxyAsyncSoap.EndGetString(System.IAsyncResult result) {
            return base.Channel.EndGetString(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetString(System.IAsyncResult result) {
            Dropthings.DiggSilverlight.DropthingsProxyService.GetStringResponse retVal = ((Dropthings.DiggSilverlight.DropthingsProxyService.ProxyAsyncSoap)(this)).EndGetString(result);
            return retVal.Body.GetStringResult;
        }
        
        private System.IAsyncResult OnBeginGetString(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string url = ((string)(inValues[0]));
            int cacheDuration = ((int)(inValues[1]));
            return this.BeginGetString(url, cacheDuration, callback, asyncState);
        }
        
        private object[] OnEndGetString(System.IAsyncResult result) {
            string retVal = this.EndGetString(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetStringCompleted(object state) {
            if ((this.GetStringCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetStringCompleted(this, new GetStringCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetStringAsync(string url, int cacheDuration) {
            this.GetStringAsync(url, cacheDuration, null);
        }
        
        public void GetStringAsync(string url, int cacheDuration, object userState) {
            if ((this.onBeginGetStringDelegate == null)) {
                this.onBeginGetStringDelegate = new BeginOperationDelegate(this.OnBeginGetString);
            }
            if ((this.onEndGetStringDelegate == null)) {
                this.onEndGetStringDelegate = new EndOperationDelegate(this.OnEndGetString);
            }
            if ((this.onGetStringCompletedDelegate == null)) {
                this.onGetStringCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetStringCompleted);
            }
            base.InvokeAsync(this.onBeginGetStringDelegate, new object[] {
                        url,
                        cacheDuration}, this.onEndGetStringDelegate, this.onGetStringCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Dropthings.DiggSilverlight.DropthingsProxyService.ProxyAsyncSoap.BeginGetXml(Dropthings.DiggSilverlight.DropthingsProxyService.GetXmlRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetXml(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetXml(string url, int cacheDuration, System.AsyncCallback callback, object asyncState) {
            Dropthings.DiggSilverlight.DropthingsProxyService.GetXmlRequest inValue = new Dropthings.DiggSilverlight.DropthingsProxyService.GetXmlRequest();
            inValue.Body = new Dropthings.DiggSilverlight.DropthingsProxyService.GetXmlRequestBody();
            inValue.Body.url = url;
            inValue.Body.cacheDuration = cacheDuration;
            return ((Dropthings.DiggSilverlight.DropthingsProxyService.ProxyAsyncSoap)(this)).BeginGetXml(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dropthings.DiggSilverlight.DropthingsProxyService.GetXmlResponse Dropthings.DiggSilverlight.DropthingsProxyService.ProxyAsyncSoap.EndGetXml(System.IAsyncResult result) {
            return base.Channel.EndGetXml(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetXml(System.IAsyncResult result) {
            Dropthings.DiggSilverlight.DropthingsProxyService.GetXmlResponse retVal = ((Dropthings.DiggSilverlight.DropthingsProxyService.ProxyAsyncSoap)(this)).EndGetXml(result);
            return retVal.Body.GetXmlResult;
        }
        
        private System.IAsyncResult OnBeginGetXml(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string url = ((string)(inValues[0]));
            int cacheDuration = ((int)(inValues[1]));
            return this.BeginGetXml(url, cacheDuration, callback, asyncState);
        }
        
        private object[] OnEndGetXml(System.IAsyncResult result) {
            string retVal = this.EndGetXml(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetXmlCompleted(object state) {
            if ((this.GetXmlCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetXmlCompleted(this, new GetXmlCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetXmlAsync(string url, int cacheDuration) {
            this.GetXmlAsync(url, cacheDuration, null);
        }
        
        public void GetXmlAsync(string url, int cacheDuration, object userState) {
            if ((this.onBeginGetXmlDelegate == null)) {
                this.onBeginGetXmlDelegate = new BeginOperationDelegate(this.OnBeginGetXml);
            }
            if ((this.onEndGetXmlDelegate == null)) {
                this.onEndGetXmlDelegate = new EndOperationDelegate(this.OnEndGetXml);
            }
            if ((this.onGetXmlCompletedDelegate == null)) {
                this.onGetXmlCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetXmlCompleted);
            }
            base.InvokeAsync(this.onBeginGetXmlDelegate, new object[] {
                        url,
                        cacheDuration}, this.onEndGetXmlDelegate, this.onGetXmlCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Dropthings.DiggSilverlight.DropthingsProxyService.ProxyAsyncSoap CreateChannel() {
            return new ProxyAsyncSoapClientChannel(this);
        }
        
        private class ProxyAsyncSoapClientChannel : ChannelBase<Dropthings.DiggSilverlight.DropthingsProxyService.ProxyAsyncSoap>, Dropthings.DiggSilverlight.DropthingsProxyService.ProxyAsyncSoap {
            
            public ProxyAsyncSoapClientChannel(System.ServiceModel.ClientBase<Dropthings.DiggSilverlight.DropthingsProxyService.ProxyAsyncSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetRss(Dropthings.DiggSilverlight.DropthingsProxyService.GetRssRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetRss", _args, callback, asyncState);
                return _result;
            }
            
            public Dropthings.DiggSilverlight.DropthingsProxyService.GetRssResponse EndGetRss(System.IAsyncResult result) {
                object[] _args = new object[0];
                Dropthings.DiggSilverlight.DropthingsProxyService.GetRssResponse _result = ((Dropthings.DiggSilverlight.DropthingsProxyService.GetRssResponse)(base.EndInvoke("GetRss", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetString(Dropthings.DiggSilverlight.DropthingsProxyService.GetStringRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetString", _args, callback, asyncState);
                return _result;
            }
            
            public Dropthings.DiggSilverlight.DropthingsProxyService.GetStringResponse EndGetString(System.IAsyncResult result) {
                object[] _args = new object[0];
                Dropthings.DiggSilverlight.DropthingsProxyService.GetStringResponse _result = ((Dropthings.DiggSilverlight.DropthingsProxyService.GetStringResponse)(base.EndInvoke("GetString", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetXml(Dropthings.DiggSilverlight.DropthingsProxyService.GetXmlRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetXml", _args, callback, asyncState);
                return _result;
            }
            
            public Dropthings.DiggSilverlight.DropthingsProxyService.GetXmlResponse EndGetXml(System.IAsyncResult result) {
                object[] _args = new object[0];
                Dropthings.DiggSilverlight.DropthingsProxyService.GetXmlResponse _result = ((Dropthings.DiggSilverlight.DropthingsProxyService.GetXmlResponse)(base.EndInvoke("GetXml", _args, result)));
                return _result;
            }
        }
    }
}
