IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Page' AND COLUMN_NAME = 'IsLocked')
BEGIN
	ALTER TABLE Page ADD IsLocked bit NULL
END

GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Page' AND COLUMN_NAME = 'IsLocked')
BEGIN
	ALTER TABLE Page ADD IsLocked bit NULL
END

GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Page' AND COLUMN_NAME = 'IsLocked')
BEGIN
	ALTER TABLE Page ADD IsLocked bit NULL
END

GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Page' AND COLUMN_NAME = 'IsLocked')
BEGIN
	ALTER TABLE Page ADD IsLocked bit NULL
END

GO