IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Page' AND COLUMN_NAME = 'IsLocked')
BEGIN
	ALTER TABLE Page ADD IsLocked bit NULL
END

GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Page' AND COLUMN_NAME = 'LockedAt')
BEGIN
	EXEC sp_RENAME 'Page.LockedAt', 'LastLockedStatusChangedAt' , 'COLUMN'
END
ELSE
BEGIN
	IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
	WHERE TABLE_NAME = 'Page' AND COLUMN_NAME = 'LastLockedStatusChangedAt')
	BEGIN
		ALTER TABLE Page ADD LastLockedStatusChangedAt datetime NULL
	END	
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Page' AND COLUMN_NAME = 'IsUnlocked')
BEGIN
	EXEC sp_RENAME 'Page.IsUnlocked', 'IsDownForMaintenance' , 'COLUMN'
END
ELSE
BEGIN
	IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
	WHERE TABLE_NAME = 'Page' AND COLUMN_NAME = 'IsDownForMaintenance')
	BEGIN
		ALTER TABLE Page ADD IsDownForMaintenance bit NULL
	END	
END
GO

IF EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Page' AND COLUMN_NAME = 'UnlockedAt')
BEGIN
		EXEC sp_RENAME 'Page.UnlockedAt', 'LastDownForMaintenanceAt' , 'COLUMN'
END
ELSE
BEGIN
	IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
	WHERE TABLE_NAME = 'Page' AND COLUMN_NAME = 'LastDownForMaintenanceAt')
	BEGIN
		ALTER TABLE Page ADD LastDownForMaintenanceAt datetime NULL
	END	
END
GO


IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Page' AND COLUMN_NAME = 'ServeAsStartPageAfterLogin')
BEGIN
	ALTER TABLE Page ADD ServeAsStartPageAfterLogin bit NULL
END

GO