//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40624.0
// 
namespace Dropthings.DiggSilverlight.DropthingsWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="DropthingsWebService.WidgetServiceSoap")]
    public interface WidgetServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AddWidgetInstance", ReplyAction="*")]
        System.IAsyncResult BeginAddWidgetInstance(int widgetId, int toZone, int toRow, System.AsyncCallback callback, object asyncState);
        
        void EndAddWidgetInstance(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/AssignPermission", ReplyAction="*")]
        System.IAsyncResult BeginAssignPermission(Dropthings.DiggSilverlight.DropthingsWebService.AssignPermissionRequest request, System.AsyncCallback callback, object asyncState);
        
        Dropthings.DiggSilverlight.DropthingsWebService.AssignPermissionResponse EndAssignPermission(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ChangePageLayout", ReplyAction="*")]
        System.IAsyncResult BeginChangePageLayout(int newLayout, System.AsyncCallback callback, object asyncState);
        
        void EndChangePageLayout(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ChangeWidgetTitle", ReplyAction="*")]
        System.IAsyncResult BeginChangeWidgetTitle(Dropthings.DiggSilverlight.DropthingsWebService.ChangeWidgetTitleRequest request, System.AsyncCallback callback, object asyncState);
        
        Dropthings.DiggSilverlight.DropthingsWebService.ChangeWidgetTitleResponse EndChangeWidgetTitle(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/CollaspeWidgetInstance", ReplyAction="*")]
        System.IAsyncResult BeginCollaspeWidgetInstance(Dropthings.DiggSilverlight.DropthingsWebService.CollaspeWidgetInstanceRequest request, System.AsyncCallback callback, object asyncState);
        
        Dropthings.DiggSilverlight.DropthingsWebService.CollaspeWidgetInstanceResponse EndCollaspeWidgetInstance(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/DeleteWidgetInstance", ReplyAction="*")]
        System.IAsyncResult BeginDeleteWidgetInstance(int widgetId, System.AsyncCallback callback, object asyncState);
        
        void EndDeleteWidgetInstance(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ExpandWidgetInstance", ReplyAction="*")]
        System.IAsyncResult BeginExpandWidgetInstance(Dropthings.DiggSilverlight.DropthingsWebService.ExpandWidgetInstanceRequest request, System.AsyncCallback callback, object asyncState);
        
        Dropthings.DiggSilverlight.DropthingsWebService.ExpandWidgetInstanceResponse EndExpandWidgetInstance(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/GetWidgetState", ReplyAction="*")]
        System.IAsyncResult BeginGetWidgetState(Dropthings.DiggSilverlight.DropthingsWebService.GetWidgetStateRequest request, System.AsyncCallback callback, object asyncState);
        
        Dropthings.DiggSilverlight.DropthingsWebService.GetWidgetStateResponse EndGetWidgetState(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/MaximizeWidgetInstance", ReplyAction="*")]
        System.IAsyncResult BeginMaximizeWidgetInstance(int widgetId, System.AsyncCallback callback, object asyncState);
        
        void EndMaximizeWidgetInstance(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/MoveWidgetInstance", ReplyAction="*")]
        System.IAsyncResult BeginMoveWidgetInstance(int instanceId, int toZoneId, int toRow, System.AsyncCallback callback, object asyncState);
        
        void EndMoveWidgetInstance(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/ResizeWidgetInstance", ReplyAction="*")]
        System.IAsyncResult BeginResizeWidgetInstance(int widgetId, int width, int height, System.AsyncCallback callback, object asyncState);
        
        void EndResizeWidgetInstance(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/RestoreWidgetInstance", ReplyAction="*")]
        System.IAsyncResult BeginRestoreWidgetInstance(int widgetId, System.AsyncCallback callback, object asyncState);
        
        void EndRestoreWidgetInstance(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="http://tempuri.org/SaveWidgetState", ReplyAction="*")]
        System.IAsyncResult BeginSaveWidgetState(Dropthings.DiggSilverlight.DropthingsWebService.SaveWidgetStateRequest request, System.AsyncCallback callback, object asyncState);
        
        Dropthings.DiggSilverlight.DropthingsWebService.SaveWidgetStateResponse EndSaveWidgetState(System.IAsyncResult result);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AssignPermissionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AssignPermission", Namespace="http://tempuri.org/", Order=0)]
        public Dropthings.DiggSilverlight.DropthingsWebService.AssignPermissionRequestBody Body;
        
        public AssignPermissionRequest() {
        }
        
        public AssignPermissionRequest(Dropthings.DiggSilverlight.DropthingsWebService.AssignPermissionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AssignPermissionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string widgetPermissions;
        
        public AssignPermissionRequestBody() {
        }
        
        public AssignPermissionRequestBody(string widgetPermissions) {
            this.widgetPermissions = widgetPermissions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AssignPermissionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AssignPermissionResponse", Namespace="http://tempuri.org/", Order=0)]
        public Dropthings.DiggSilverlight.DropthingsWebService.AssignPermissionResponseBody Body;
        
        public AssignPermissionResponse() {
        }
        
        public AssignPermissionResponse(Dropthings.DiggSilverlight.DropthingsWebService.AssignPermissionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class AssignPermissionResponseBody {
        
        public AssignPermissionResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeWidgetTitleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeWidgetTitle", Namespace="http://tempuri.org/", Order=0)]
        public Dropthings.DiggSilverlight.DropthingsWebService.ChangeWidgetTitleRequestBody Body;
        
        public ChangeWidgetTitleRequest() {
        }
        
        public ChangeWidgetTitleRequest(Dropthings.DiggSilverlight.DropthingsWebService.ChangeWidgetTitleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ChangeWidgetTitleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int widgetId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string newTitle;
        
        public ChangeWidgetTitleRequestBody() {
        }
        
        public ChangeWidgetTitleRequestBody(int widgetId, string newTitle) {
            this.widgetId = widgetId;
            this.newTitle = newTitle;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ChangeWidgetTitleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ChangeWidgetTitleResponse", Namespace="http://tempuri.org/", Order=0)]
        public Dropthings.DiggSilverlight.DropthingsWebService.ChangeWidgetTitleResponseBody Body;
        
        public ChangeWidgetTitleResponse() {
        }
        
        public ChangeWidgetTitleResponse(Dropthings.DiggSilverlight.DropthingsWebService.ChangeWidgetTitleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ChangeWidgetTitleResponseBody {
        
        public ChangeWidgetTitleResponseBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CollaspeWidgetInstanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CollaspeWidgetInstance", Namespace="http://tempuri.org/", Order=0)]
        public Dropthings.DiggSilverlight.DropthingsWebService.CollaspeWidgetInstanceRequestBody Body;
        
        public CollaspeWidgetInstanceRequest() {
        }
        
        public CollaspeWidgetInstanceRequest(Dropthings.DiggSilverlight.DropthingsWebService.CollaspeWidgetInstanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CollaspeWidgetInstanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int widgetId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string postbackUrl;
        
        public CollaspeWidgetInstanceRequestBody() {
        }
        
        public CollaspeWidgetInstanceRequestBody(int widgetId, string postbackUrl) {
            this.widgetId = widgetId;
            this.postbackUrl = postbackUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CollaspeWidgetInstanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CollaspeWidgetInstanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public Dropthings.DiggSilverlight.DropthingsWebService.CollaspeWidgetInstanceResponseBody Body;
        
        public CollaspeWidgetInstanceResponse() {
        }
        
        public CollaspeWidgetInstanceResponse(Dropthings.DiggSilverlight.DropthingsWebService.CollaspeWidgetInstanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CollaspeWidgetInstanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CollaspeWidgetInstanceResult;
        
        public CollaspeWidgetInstanceResponseBody() {
        }
        
        public CollaspeWidgetInstanceResponseBody(string CollaspeWidgetInstanceResult) {
            this.CollaspeWidgetInstanceResult = CollaspeWidgetInstanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExpandWidgetInstanceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExpandWidgetInstance", Namespace="http://tempuri.org/", Order=0)]
        public Dropthings.DiggSilverlight.DropthingsWebService.ExpandWidgetInstanceRequestBody Body;
        
        public ExpandWidgetInstanceRequest() {
        }
        
        public ExpandWidgetInstanceRequest(Dropthings.DiggSilverlight.DropthingsWebService.ExpandWidgetInstanceRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExpandWidgetInstanceRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int widgetId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string postbackUrl;
        
        public ExpandWidgetInstanceRequestBody() {
        }
        
        public ExpandWidgetInstanceRequestBody(int widgetId, string postbackUrl) {
            this.widgetId = widgetId;
            this.postbackUrl = postbackUrl;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ExpandWidgetInstanceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ExpandWidgetInstanceResponse", Namespace="http://tempuri.org/", Order=0)]
        public Dropthings.DiggSilverlight.DropthingsWebService.ExpandWidgetInstanceResponseBody Body;
        
        public ExpandWidgetInstanceResponse() {
        }
        
        public ExpandWidgetInstanceResponse(Dropthings.DiggSilverlight.DropthingsWebService.ExpandWidgetInstanceResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ExpandWidgetInstanceResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ExpandWidgetInstanceResult;
        
        public ExpandWidgetInstanceResponseBody() {
        }
        
        public ExpandWidgetInstanceResponseBody(string ExpandWidgetInstanceResult) {
            this.ExpandWidgetInstanceResult = ExpandWidgetInstanceResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWidgetStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWidgetState", Namespace="http://tempuri.org/", Order=0)]
        public Dropthings.DiggSilverlight.DropthingsWebService.GetWidgetStateRequestBody Body;
        
        public GetWidgetStateRequest() {
        }
        
        public GetWidgetStateRequest(Dropthings.DiggSilverlight.DropthingsWebService.GetWidgetStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWidgetStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int widgetId;
        
        public GetWidgetStateRequestBody() {
        }
        
        public GetWidgetStateRequestBody(int widgetId) {
            this.widgetId = widgetId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetWidgetStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetWidgetStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Dropthings.DiggSilverlight.DropthingsWebService.GetWidgetStateResponseBody Body;
        
        public GetWidgetStateResponse() {
        }
        
        public GetWidgetStateResponse(Dropthings.DiggSilverlight.DropthingsWebService.GetWidgetStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetWidgetStateResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetWidgetStateResult;
        
        public GetWidgetStateResponseBody() {
        }
        
        public GetWidgetStateResponseBody(string GetWidgetStateResult) {
            this.GetWidgetStateResult = GetWidgetStateResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveWidgetStateRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveWidgetState", Namespace="http://tempuri.org/", Order=0)]
        public Dropthings.DiggSilverlight.DropthingsWebService.SaveWidgetStateRequestBody Body;
        
        public SaveWidgetStateRequest() {
        }
        
        public SaveWidgetStateRequest(Dropthings.DiggSilverlight.DropthingsWebService.SaveWidgetStateRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaveWidgetStateRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int widgetId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string state;
        
        public SaveWidgetStateRequestBody() {
        }
        
        public SaveWidgetStateRequestBody(int widgetId, string state) {
            this.widgetId = widgetId;
            this.state = state;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaveWidgetStateResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaveWidgetStateResponse", Namespace="http://tempuri.org/", Order=0)]
        public Dropthings.DiggSilverlight.DropthingsWebService.SaveWidgetStateResponseBody Body;
        
        public SaveWidgetStateResponse() {
        }
        
        public SaveWidgetStateResponse(Dropthings.DiggSilverlight.DropthingsWebService.SaveWidgetStateResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class SaveWidgetStateResponseBody {
        
        public SaveWidgetStateResponseBody() {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface WidgetServiceSoapChannel : Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class CollaspeWidgetInstanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CollaspeWidgetInstanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class ExpandWidgetInstanceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public ExpandWidgetInstanceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetWidgetStateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetWidgetStateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public string Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class WidgetServiceSoapClient : System.ServiceModel.ClientBase<Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap>, Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap {
        
        private BeginOperationDelegate onBeginAddWidgetInstanceDelegate;
        
        private EndOperationDelegate onEndAddWidgetInstanceDelegate;
        
        private System.Threading.SendOrPostCallback onAddWidgetInstanceCompletedDelegate;
        
        private BeginOperationDelegate onBeginAssignPermissionDelegate;
        
        private EndOperationDelegate onEndAssignPermissionDelegate;
        
        private System.Threading.SendOrPostCallback onAssignPermissionCompletedDelegate;
        
        private BeginOperationDelegate onBeginChangePageLayoutDelegate;
        
        private EndOperationDelegate onEndChangePageLayoutDelegate;
        
        private System.Threading.SendOrPostCallback onChangePageLayoutCompletedDelegate;
        
        private BeginOperationDelegate onBeginChangeWidgetTitleDelegate;
        
        private EndOperationDelegate onEndChangeWidgetTitleDelegate;
        
        private System.Threading.SendOrPostCallback onChangeWidgetTitleCompletedDelegate;
        
        private BeginOperationDelegate onBeginCollaspeWidgetInstanceDelegate;
        
        private EndOperationDelegate onEndCollaspeWidgetInstanceDelegate;
        
        private System.Threading.SendOrPostCallback onCollaspeWidgetInstanceCompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteWidgetInstanceDelegate;
        
        private EndOperationDelegate onEndDeleteWidgetInstanceDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteWidgetInstanceCompletedDelegate;
        
        private BeginOperationDelegate onBeginExpandWidgetInstanceDelegate;
        
        private EndOperationDelegate onEndExpandWidgetInstanceDelegate;
        
        private System.Threading.SendOrPostCallback onExpandWidgetInstanceCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetWidgetStateDelegate;
        
        private EndOperationDelegate onEndGetWidgetStateDelegate;
        
        private System.Threading.SendOrPostCallback onGetWidgetStateCompletedDelegate;
        
        private BeginOperationDelegate onBeginMaximizeWidgetInstanceDelegate;
        
        private EndOperationDelegate onEndMaximizeWidgetInstanceDelegate;
        
        private System.Threading.SendOrPostCallback onMaximizeWidgetInstanceCompletedDelegate;
        
        private BeginOperationDelegate onBeginMoveWidgetInstanceDelegate;
        
        private EndOperationDelegate onEndMoveWidgetInstanceDelegate;
        
        private System.Threading.SendOrPostCallback onMoveWidgetInstanceCompletedDelegate;
        
        private BeginOperationDelegate onBeginResizeWidgetInstanceDelegate;
        
        private EndOperationDelegate onEndResizeWidgetInstanceDelegate;
        
        private System.Threading.SendOrPostCallback onResizeWidgetInstanceCompletedDelegate;
        
        private BeginOperationDelegate onBeginRestoreWidgetInstanceDelegate;
        
        private EndOperationDelegate onEndRestoreWidgetInstanceDelegate;
        
        private System.Threading.SendOrPostCallback onRestoreWidgetInstanceCompletedDelegate;
        
        private BeginOperationDelegate onBeginSaveWidgetStateDelegate;
        
        private EndOperationDelegate onEndSaveWidgetStateDelegate;
        
        private System.Threading.SendOrPostCallback onSaveWidgetStateCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public WidgetServiceSoapClient() {
        }
        
        public WidgetServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WidgetServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WidgetServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WidgetServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AddWidgetInstanceCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> AssignPermissionCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ChangePageLayoutCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ChangeWidgetTitleCompleted;
        
        public event System.EventHandler<CollaspeWidgetInstanceCompletedEventArgs> CollaspeWidgetInstanceCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteWidgetInstanceCompleted;
        
        public event System.EventHandler<ExpandWidgetInstanceCompletedEventArgs> ExpandWidgetInstanceCompleted;
        
        public event System.EventHandler<GetWidgetStateCompletedEventArgs> GetWidgetStateCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> MaximizeWidgetInstanceCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> MoveWidgetInstanceCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> ResizeWidgetInstanceCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> RestoreWidgetInstanceCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> SaveWidgetStateCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.BeginAddWidgetInstance(int widgetId, int toZone, int toRow, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAddWidgetInstance(widgetId, toZone, toRow, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.EndAddWidgetInstance(System.IAsyncResult result) {
            base.Channel.EndAddWidgetInstance(result);
        }
        
        private System.IAsyncResult OnBeginAddWidgetInstance(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int widgetId = ((int)(inValues[0]));
            int toZone = ((int)(inValues[1]));
            int toRow = ((int)(inValues[2]));
            return ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).BeginAddWidgetInstance(widgetId, toZone, toRow, callback, asyncState);
        }
        
        private object[] OnEndAddWidgetInstance(System.IAsyncResult result) {
            ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).EndAddWidgetInstance(result);
            return null;
        }
        
        private void OnAddWidgetInstanceCompleted(object state) {
            if ((this.AddWidgetInstanceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AddWidgetInstanceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AddWidgetInstanceAsync(int widgetId, int toZone, int toRow) {
            this.AddWidgetInstanceAsync(widgetId, toZone, toRow, null);
        }
        
        public void AddWidgetInstanceAsync(int widgetId, int toZone, int toRow, object userState) {
            if ((this.onBeginAddWidgetInstanceDelegate == null)) {
                this.onBeginAddWidgetInstanceDelegate = new BeginOperationDelegate(this.OnBeginAddWidgetInstance);
            }
            if ((this.onEndAddWidgetInstanceDelegate == null)) {
                this.onEndAddWidgetInstanceDelegate = new EndOperationDelegate(this.OnEndAddWidgetInstance);
            }
            if ((this.onAddWidgetInstanceCompletedDelegate == null)) {
                this.onAddWidgetInstanceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAddWidgetInstanceCompleted);
            }
            base.InvokeAsync(this.onBeginAddWidgetInstanceDelegate, new object[] {
                        widgetId,
                        toZone,
                        toRow}, this.onEndAddWidgetInstanceDelegate, this.onAddWidgetInstanceCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.BeginAssignPermission(Dropthings.DiggSilverlight.DropthingsWebService.AssignPermissionRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginAssignPermission(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginAssignPermission(string widgetPermissions, System.AsyncCallback callback, object asyncState) {
            Dropthings.DiggSilverlight.DropthingsWebService.AssignPermissionRequest inValue = new Dropthings.DiggSilverlight.DropthingsWebService.AssignPermissionRequest();
            inValue.Body = new Dropthings.DiggSilverlight.DropthingsWebService.AssignPermissionRequestBody();
            inValue.Body.widgetPermissions = widgetPermissions;
            return ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).BeginAssignPermission(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dropthings.DiggSilverlight.DropthingsWebService.AssignPermissionResponse Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.EndAssignPermission(System.IAsyncResult result) {
            return base.Channel.EndAssignPermission(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void EndAssignPermission(System.IAsyncResult result) {
            Dropthings.DiggSilverlight.DropthingsWebService.AssignPermissionResponse retVal = ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).EndAssignPermission(result);
        }
        
        private System.IAsyncResult OnBeginAssignPermission(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string widgetPermissions = ((string)(inValues[0]));
            return this.BeginAssignPermission(widgetPermissions, callback, asyncState);
        }
        
        private object[] OnEndAssignPermission(System.IAsyncResult result) {
            this.EndAssignPermission(result);
            return null;
        }
        
        private void OnAssignPermissionCompleted(object state) {
            if ((this.AssignPermissionCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.AssignPermissionCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void AssignPermissionAsync(string widgetPermissions) {
            this.AssignPermissionAsync(widgetPermissions, null);
        }
        
        public void AssignPermissionAsync(string widgetPermissions, object userState) {
            if ((this.onBeginAssignPermissionDelegate == null)) {
                this.onBeginAssignPermissionDelegate = new BeginOperationDelegate(this.OnBeginAssignPermission);
            }
            if ((this.onEndAssignPermissionDelegate == null)) {
                this.onEndAssignPermissionDelegate = new EndOperationDelegate(this.OnEndAssignPermission);
            }
            if ((this.onAssignPermissionCompletedDelegate == null)) {
                this.onAssignPermissionCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnAssignPermissionCompleted);
            }
            base.InvokeAsync(this.onBeginAssignPermissionDelegate, new object[] {
                        widgetPermissions}, this.onEndAssignPermissionDelegate, this.onAssignPermissionCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.BeginChangePageLayout(int newLayout, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginChangePageLayout(newLayout, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.EndChangePageLayout(System.IAsyncResult result) {
            base.Channel.EndChangePageLayout(result);
        }
        
        private System.IAsyncResult OnBeginChangePageLayout(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int newLayout = ((int)(inValues[0]));
            return ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).BeginChangePageLayout(newLayout, callback, asyncState);
        }
        
        private object[] OnEndChangePageLayout(System.IAsyncResult result) {
            ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).EndChangePageLayout(result);
            return null;
        }
        
        private void OnChangePageLayoutCompleted(object state) {
            if ((this.ChangePageLayoutCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ChangePageLayoutCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ChangePageLayoutAsync(int newLayout) {
            this.ChangePageLayoutAsync(newLayout, null);
        }
        
        public void ChangePageLayoutAsync(int newLayout, object userState) {
            if ((this.onBeginChangePageLayoutDelegate == null)) {
                this.onBeginChangePageLayoutDelegate = new BeginOperationDelegate(this.OnBeginChangePageLayout);
            }
            if ((this.onEndChangePageLayoutDelegate == null)) {
                this.onEndChangePageLayoutDelegate = new EndOperationDelegate(this.OnEndChangePageLayout);
            }
            if ((this.onChangePageLayoutCompletedDelegate == null)) {
                this.onChangePageLayoutCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnChangePageLayoutCompleted);
            }
            base.InvokeAsync(this.onBeginChangePageLayoutDelegate, new object[] {
                        newLayout}, this.onEndChangePageLayoutDelegate, this.onChangePageLayoutCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.BeginChangeWidgetTitle(Dropthings.DiggSilverlight.DropthingsWebService.ChangeWidgetTitleRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginChangeWidgetTitle(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginChangeWidgetTitle(int widgetId, string newTitle, System.AsyncCallback callback, object asyncState) {
            Dropthings.DiggSilverlight.DropthingsWebService.ChangeWidgetTitleRequest inValue = new Dropthings.DiggSilverlight.DropthingsWebService.ChangeWidgetTitleRequest();
            inValue.Body = new Dropthings.DiggSilverlight.DropthingsWebService.ChangeWidgetTitleRequestBody();
            inValue.Body.widgetId = widgetId;
            inValue.Body.newTitle = newTitle;
            return ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).BeginChangeWidgetTitle(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dropthings.DiggSilverlight.DropthingsWebService.ChangeWidgetTitleResponse Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.EndChangeWidgetTitle(System.IAsyncResult result) {
            return base.Channel.EndChangeWidgetTitle(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void EndChangeWidgetTitle(System.IAsyncResult result) {
            Dropthings.DiggSilverlight.DropthingsWebService.ChangeWidgetTitleResponse retVal = ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).EndChangeWidgetTitle(result);
        }
        
        private System.IAsyncResult OnBeginChangeWidgetTitle(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int widgetId = ((int)(inValues[0]));
            string newTitle = ((string)(inValues[1]));
            return this.BeginChangeWidgetTitle(widgetId, newTitle, callback, asyncState);
        }
        
        private object[] OnEndChangeWidgetTitle(System.IAsyncResult result) {
            this.EndChangeWidgetTitle(result);
            return null;
        }
        
        private void OnChangeWidgetTitleCompleted(object state) {
            if ((this.ChangeWidgetTitleCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ChangeWidgetTitleCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ChangeWidgetTitleAsync(int widgetId, string newTitle) {
            this.ChangeWidgetTitleAsync(widgetId, newTitle, null);
        }
        
        public void ChangeWidgetTitleAsync(int widgetId, string newTitle, object userState) {
            if ((this.onBeginChangeWidgetTitleDelegate == null)) {
                this.onBeginChangeWidgetTitleDelegate = new BeginOperationDelegate(this.OnBeginChangeWidgetTitle);
            }
            if ((this.onEndChangeWidgetTitleDelegate == null)) {
                this.onEndChangeWidgetTitleDelegate = new EndOperationDelegate(this.OnEndChangeWidgetTitle);
            }
            if ((this.onChangeWidgetTitleCompletedDelegate == null)) {
                this.onChangeWidgetTitleCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnChangeWidgetTitleCompleted);
            }
            base.InvokeAsync(this.onBeginChangeWidgetTitleDelegate, new object[] {
                        widgetId,
                        newTitle}, this.onEndChangeWidgetTitleDelegate, this.onChangeWidgetTitleCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.BeginCollaspeWidgetInstance(Dropthings.DiggSilverlight.DropthingsWebService.CollaspeWidgetInstanceRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCollaspeWidgetInstance(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginCollaspeWidgetInstance(int widgetId, string postbackUrl, System.AsyncCallback callback, object asyncState) {
            Dropthings.DiggSilverlight.DropthingsWebService.CollaspeWidgetInstanceRequest inValue = new Dropthings.DiggSilverlight.DropthingsWebService.CollaspeWidgetInstanceRequest();
            inValue.Body = new Dropthings.DiggSilverlight.DropthingsWebService.CollaspeWidgetInstanceRequestBody();
            inValue.Body.widgetId = widgetId;
            inValue.Body.postbackUrl = postbackUrl;
            return ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).BeginCollaspeWidgetInstance(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dropthings.DiggSilverlight.DropthingsWebService.CollaspeWidgetInstanceResponse Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.EndCollaspeWidgetInstance(System.IAsyncResult result) {
            return base.Channel.EndCollaspeWidgetInstance(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndCollaspeWidgetInstance(System.IAsyncResult result) {
            Dropthings.DiggSilverlight.DropthingsWebService.CollaspeWidgetInstanceResponse retVal = ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).EndCollaspeWidgetInstance(result);
            return retVal.Body.CollaspeWidgetInstanceResult;
        }
        
        private System.IAsyncResult OnBeginCollaspeWidgetInstance(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int widgetId = ((int)(inValues[0]));
            string postbackUrl = ((string)(inValues[1]));
            return this.BeginCollaspeWidgetInstance(widgetId, postbackUrl, callback, asyncState);
        }
        
        private object[] OnEndCollaspeWidgetInstance(System.IAsyncResult result) {
            string retVal = this.EndCollaspeWidgetInstance(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCollaspeWidgetInstanceCompleted(object state) {
            if ((this.CollaspeWidgetInstanceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CollaspeWidgetInstanceCompleted(this, new CollaspeWidgetInstanceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CollaspeWidgetInstanceAsync(int widgetId, string postbackUrl) {
            this.CollaspeWidgetInstanceAsync(widgetId, postbackUrl, null);
        }
        
        public void CollaspeWidgetInstanceAsync(int widgetId, string postbackUrl, object userState) {
            if ((this.onBeginCollaspeWidgetInstanceDelegate == null)) {
                this.onBeginCollaspeWidgetInstanceDelegate = new BeginOperationDelegate(this.OnBeginCollaspeWidgetInstance);
            }
            if ((this.onEndCollaspeWidgetInstanceDelegate == null)) {
                this.onEndCollaspeWidgetInstanceDelegate = new EndOperationDelegate(this.OnEndCollaspeWidgetInstance);
            }
            if ((this.onCollaspeWidgetInstanceCompletedDelegate == null)) {
                this.onCollaspeWidgetInstanceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCollaspeWidgetInstanceCompleted);
            }
            base.InvokeAsync(this.onBeginCollaspeWidgetInstanceDelegate, new object[] {
                        widgetId,
                        postbackUrl}, this.onEndCollaspeWidgetInstanceDelegate, this.onCollaspeWidgetInstanceCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.BeginDeleteWidgetInstance(int widgetId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteWidgetInstance(widgetId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.EndDeleteWidgetInstance(System.IAsyncResult result) {
            base.Channel.EndDeleteWidgetInstance(result);
        }
        
        private System.IAsyncResult OnBeginDeleteWidgetInstance(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int widgetId = ((int)(inValues[0]));
            return ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).BeginDeleteWidgetInstance(widgetId, callback, asyncState);
        }
        
        private object[] OnEndDeleteWidgetInstance(System.IAsyncResult result) {
            ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).EndDeleteWidgetInstance(result);
            return null;
        }
        
        private void OnDeleteWidgetInstanceCompleted(object state) {
            if ((this.DeleteWidgetInstanceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteWidgetInstanceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteWidgetInstanceAsync(int widgetId) {
            this.DeleteWidgetInstanceAsync(widgetId, null);
        }
        
        public void DeleteWidgetInstanceAsync(int widgetId, object userState) {
            if ((this.onBeginDeleteWidgetInstanceDelegate == null)) {
                this.onBeginDeleteWidgetInstanceDelegate = new BeginOperationDelegate(this.OnBeginDeleteWidgetInstance);
            }
            if ((this.onEndDeleteWidgetInstanceDelegate == null)) {
                this.onEndDeleteWidgetInstanceDelegate = new EndOperationDelegate(this.OnEndDeleteWidgetInstance);
            }
            if ((this.onDeleteWidgetInstanceCompletedDelegate == null)) {
                this.onDeleteWidgetInstanceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteWidgetInstanceCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteWidgetInstanceDelegate, new object[] {
                        widgetId}, this.onEndDeleteWidgetInstanceDelegate, this.onDeleteWidgetInstanceCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.BeginExpandWidgetInstance(Dropthings.DiggSilverlight.DropthingsWebService.ExpandWidgetInstanceRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginExpandWidgetInstance(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginExpandWidgetInstance(int widgetId, string postbackUrl, System.AsyncCallback callback, object asyncState) {
            Dropthings.DiggSilverlight.DropthingsWebService.ExpandWidgetInstanceRequest inValue = new Dropthings.DiggSilverlight.DropthingsWebService.ExpandWidgetInstanceRequest();
            inValue.Body = new Dropthings.DiggSilverlight.DropthingsWebService.ExpandWidgetInstanceRequestBody();
            inValue.Body.widgetId = widgetId;
            inValue.Body.postbackUrl = postbackUrl;
            return ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).BeginExpandWidgetInstance(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dropthings.DiggSilverlight.DropthingsWebService.ExpandWidgetInstanceResponse Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.EndExpandWidgetInstance(System.IAsyncResult result) {
            return base.Channel.EndExpandWidgetInstance(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndExpandWidgetInstance(System.IAsyncResult result) {
            Dropthings.DiggSilverlight.DropthingsWebService.ExpandWidgetInstanceResponse retVal = ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).EndExpandWidgetInstance(result);
            return retVal.Body.ExpandWidgetInstanceResult;
        }
        
        private System.IAsyncResult OnBeginExpandWidgetInstance(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int widgetId = ((int)(inValues[0]));
            string postbackUrl = ((string)(inValues[1]));
            return this.BeginExpandWidgetInstance(widgetId, postbackUrl, callback, asyncState);
        }
        
        private object[] OnEndExpandWidgetInstance(System.IAsyncResult result) {
            string retVal = this.EndExpandWidgetInstance(result);
            return new object[] {
                    retVal};
        }
        
        private void OnExpandWidgetInstanceCompleted(object state) {
            if ((this.ExpandWidgetInstanceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ExpandWidgetInstanceCompleted(this, new ExpandWidgetInstanceCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ExpandWidgetInstanceAsync(int widgetId, string postbackUrl) {
            this.ExpandWidgetInstanceAsync(widgetId, postbackUrl, null);
        }
        
        public void ExpandWidgetInstanceAsync(int widgetId, string postbackUrl, object userState) {
            if ((this.onBeginExpandWidgetInstanceDelegate == null)) {
                this.onBeginExpandWidgetInstanceDelegate = new BeginOperationDelegate(this.OnBeginExpandWidgetInstance);
            }
            if ((this.onEndExpandWidgetInstanceDelegate == null)) {
                this.onEndExpandWidgetInstanceDelegate = new EndOperationDelegate(this.OnEndExpandWidgetInstance);
            }
            if ((this.onExpandWidgetInstanceCompletedDelegate == null)) {
                this.onExpandWidgetInstanceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnExpandWidgetInstanceCompleted);
            }
            base.InvokeAsync(this.onBeginExpandWidgetInstanceDelegate, new object[] {
                        widgetId,
                        postbackUrl}, this.onEndExpandWidgetInstanceDelegate, this.onExpandWidgetInstanceCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.BeginGetWidgetState(Dropthings.DiggSilverlight.DropthingsWebService.GetWidgetStateRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetWidgetState(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginGetWidgetState(int widgetId, System.AsyncCallback callback, object asyncState) {
            Dropthings.DiggSilverlight.DropthingsWebService.GetWidgetStateRequest inValue = new Dropthings.DiggSilverlight.DropthingsWebService.GetWidgetStateRequest();
            inValue.Body = new Dropthings.DiggSilverlight.DropthingsWebService.GetWidgetStateRequestBody();
            inValue.Body.widgetId = widgetId;
            return ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).BeginGetWidgetState(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dropthings.DiggSilverlight.DropthingsWebService.GetWidgetStateResponse Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.EndGetWidgetState(System.IAsyncResult result) {
            return base.Channel.EndGetWidgetState(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private string EndGetWidgetState(System.IAsyncResult result) {
            Dropthings.DiggSilverlight.DropthingsWebService.GetWidgetStateResponse retVal = ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).EndGetWidgetState(result);
            return retVal.Body.GetWidgetStateResult;
        }
        
        private System.IAsyncResult OnBeginGetWidgetState(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int widgetId = ((int)(inValues[0]));
            return this.BeginGetWidgetState(widgetId, callback, asyncState);
        }
        
        private object[] OnEndGetWidgetState(System.IAsyncResult result) {
            string retVal = this.EndGetWidgetState(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetWidgetStateCompleted(object state) {
            if ((this.GetWidgetStateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetWidgetStateCompleted(this, new GetWidgetStateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetWidgetStateAsync(int widgetId) {
            this.GetWidgetStateAsync(widgetId, null);
        }
        
        public void GetWidgetStateAsync(int widgetId, object userState) {
            if ((this.onBeginGetWidgetStateDelegate == null)) {
                this.onBeginGetWidgetStateDelegate = new BeginOperationDelegate(this.OnBeginGetWidgetState);
            }
            if ((this.onEndGetWidgetStateDelegate == null)) {
                this.onEndGetWidgetStateDelegate = new EndOperationDelegate(this.OnEndGetWidgetState);
            }
            if ((this.onGetWidgetStateCompletedDelegate == null)) {
                this.onGetWidgetStateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetWidgetStateCompleted);
            }
            base.InvokeAsync(this.onBeginGetWidgetStateDelegate, new object[] {
                        widgetId}, this.onEndGetWidgetStateDelegate, this.onGetWidgetStateCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.BeginMaximizeWidgetInstance(int widgetId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginMaximizeWidgetInstance(widgetId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.EndMaximizeWidgetInstance(System.IAsyncResult result) {
            base.Channel.EndMaximizeWidgetInstance(result);
        }
        
        private System.IAsyncResult OnBeginMaximizeWidgetInstance(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int widgetId = ((int)(inValues[0]));
            return ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).BeginMaximizeWidgetInstance(widgetId, callback, asyncState);
        }
        
        private object[] OnEndMaximizeWidgetInstance(System.IAsyncResult result) {
            ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).EndMaximizeWidgetInstance(result);
            return null;
        }
        
        private void OnMaximizeWidgetInstanceCompleted(object state) {
            if ((this.MaximizeWidgetInstanceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.MaximizeWidgetInstanceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void MaximizeWidgetInstanceAsync(int widgetId) {
            this.MaximizeWidgetInstanceAsync(widgetId, null);
        }
        
        public void MaximizeWidgetInstanceAsync(int widgetId, object userState) {
            if ((this.onBeginMaximizeWidgetInstanceDelegate == null)) {
                this.onBeginMaximizeWidgetInstanceDelegate = new BeginOperationDelegate(this.OnBeginMaximizeWidgetInstance);
            }
            if ((this.onEndMaximizeWidgetInstanceDelegate == null)) {
                this.onEndMaximizeWidgetInstanceDelegate = new EndOperationDelegate(this.OnEndMaximizeWidgetInstance);
            }
            if ((this.onMaximizeWidgetInstanceCompletedDelegate == null)) {
                this.onMaximizeWidgetInstanceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnMaximizeWidgetInstanceCompleted);
            }
            base.InvokeAsync(this.onBeginMaximizeWidgetInstanceDelegate, new object[] {
                        widgetId}, this.onEndMaximizeWidgetInstanceDelegate, this.onMaximizeWidgetInstanceCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.BeginMoveWidgetInstance(int instanceId, int toZoneId, int toRow, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginMoveWidgetInstance(instanceId, toZoneId, toRow, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.EndMoveWidgetInstance(System.IAsyncResult result) {
            base.Channel.EndMoveWidgetInstance(result);
        }
        
        private System.IAsyncResult OnBeginMoveWidgetInstance(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int instanceId = ((int)(inValues[0]));
            int toZoneId = ((int)(inValues[1]));
            int toRow = ((int)(inValues[2]));
            return ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).BeginMoveWidgetInstance(instanceId, toZoneId, toRow, callback, asyncState);
        }
        
        private object[] OnEndMoveWidgetInstance(System.IAsyncResult result) {
            ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).EndMoveWidgetInstance(result);
            return null;
        }
        
        private void OnMoveWidgetInstanceCompleted(object state) {
            if ((this.MoveWidgetInstanceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.MoveWidgetInstanceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void MoveWidgetInstanceAsync(int instanceId, int toZoneId, int toRow) {
            this.MoveWidgetInstanceAsync(instanceId, toZoneId, toRow, null);
        }
        
        public void MoveWidgetInstanceAsync(int instanceId, int toZoneId, int toRow, object userState) {
            if ((this.onBeginMoveWidgetInstanceDelegate == null)) {
                this.onBeginMoveWidgetInstanceDelegate = new BeginOperationDelegate(this.OnBeginMoveWidgetInstance);
            }
            if ((this.onEndMoveWidgetInstanceDelegate == null)) {
                this.onEndMoveWidgetInstanceDelegate = new EndOperationDelegate(this.OnEndMoveWidgetInstance);
            }
            if ((this.onMoveWidgetInstanceCompletedDelegate == null)) {
                this.onMoveWidgetInstanceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnMoveWidgetInstanceCompleted);
            }
            base.InvokeAsync(this.onBeginMoveWidgetInstanceDelegate, new object[] {
                        instanceId,
                        toZoneId,
                        toRow}, this.onEndMoveWidgetInstanceDelegate, this.onMoveWidgetInstanceCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.BeginResizeWidgetInstance(int widgetId, int width, int height, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginResizeWidgetInstance(widgetId, width, height, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.EndResizeWidgetInstance(System.IAsyncResult result) {
            base.Channel.EndResizeWidgetInstance(result);
        }
        
        private System.IAsyncResult OnBeginResizeWidgetInstance(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int widgetId = ((int)(inValues[0]));
            int width = ((int)(inValues[1]));
            int height = ((int)(inValues[2]));
            return ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).BeginResizeWidgetInstance(widgetId, width, height, callback, asyncState);
        }
        
        private object[] OnEndResizeWidgetInstance(System.IAsyncResult result) {
            ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).EndResizeWidgetInstance(result);
            return null;
        }
        
        private void OnResizeWidgetInstanceCompleted(object state) {
            if ((this.ResizeWidgetInstanceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.ResizeWidgetInstanceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void ResizeWidgetInstanceAsync(int widgetId, int width, int height) {
            this.ResizeWidgetInstanceAsync(widgetId, width, height, null);
        }
        
        public void ResizeWidgetInstanceAsync(int widgetId, int width, int height, object userState) {
            if ((this.onBeginResizeWidgetInstanceDelegate == null)) {
                this.onBeginResizeWidgetInstanceDelegate = new BeginOperationDelegate(this.OnBeginResizeWidgetInstance);
            }
            if ((this.onEndResizeWidgetInstanceDelegate == null)) {
                this.onEndResizeWidgetInstanceDelegate = new EndOperationDelegate(this.OnEndResizeWidgetInstance);
            }
            if ((this.onResizeWidgetInstanceCompletedDelegate == null)) {
                this.onResizeWidgetInstanceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnResizeWidgetInstanceCompleted);
            }
            base.InvokeAsync(this.onBeginResizeWidgetInstanceDelegate, new object[] {
                        widgetId,
                        width,
                        height}, this.onEndResizeWidgetInstanceDelegate, this.onResizeWidgetInstanceCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.BeginRestoreWidgetInstance(int widgetId, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginRestoreWidgetInstance(widgetId, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.EndRestoreWidgetInstance(System.IAsyncResult result) {
            base.Channel.EndRestoreWidgetInstance(result);
        }
        
        private System.IAsyncResult OnBeginRestoreWidgetInstance(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int widgetId = ((int)(inValues[0]));
            return ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).BeginRestoreWidgetInstance(widgetId, callback, asyncState);
        }
        
        private object[] OnEndRestoreWidgetInstance(System.IAsyncResult result) {
            ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).EndRestoreWidgetInstance(result);
            return null;
        }
        
        private void OnRestoreWidgetInstanceCompleted(object state) {
            if ((this.RestoreWidgetInstanceCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.RestoreWidgetInstanceCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void RestoreWidgetInstanceAsync(int widgetId) {
            this.RestoreWidgetInstanceAsync(widgetId, null);
        }
        
        public void RestoreWidgetInstanceAsync(int widgetId, object userState) {
            if ((this.onBeginRestoreWidgetInstanceDelegate == null)) {
                this.onBeginRestoreWidgetInstanceDelegate = new BeginOperationDelegate(this.OnBeginRestoreWidgetInstance);
            }
            if ((this.onEndRestoreWidgetInstanceDelegate == null)) {
                this.onEndRestoreWidgetInstanceDelegate = new EndOperationDelegate(this.OnEndRestoreWidgetInstance);
            }
            if ((this.onRestoreWidgetInstanceCompletedDelegate == null)) {
                this.onRestoreWidgetInstanceCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnRestoreWidgetInstanceCompleted);
            }
            base.InvokeAsync(this.onBeginRestoreWidgetInstanceDelegate, new object[] {
                        widgetId}, this.onEndRestoreWidgetInstanceDelegate, this.onRestoreWidgetInstanceCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.BeginSaveWidgetState(Dropthings.DiggSilverlight.DropthingsWebService.SaveWidgetStateRequest request, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginSaveWidgetState(request, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private System.IAsyncResult BeginSaveWidgetState(int widgetId, string state, System.AsyncCallback callback, object asyncState) {
            Dropthings.DiggSilverlight.DropthingsWebService.SaveWidgetStateRequest inValue = new Dropthings.DiggSilverlight.DropthingsWebService.SaveWidgetStateRequest();
            inValue.Body = new Dropthings.DiggSilverlight.DropthingsWebService.SaveWidgetStateRequestBody();
            inValue.Body.widgetId = widgetId;
            inValue.Body.state = state;
            return ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).BeginSaveWidgetState(inValue, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Dropthings.DiggSilverlight.DropthingsWebService.SaveWidgetStateResponse Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap.EndSaveWidgetState(System.IAsyncResult result) {
            return base.Channel.EndSaveWidgetState(result);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void EndSaveWidgetState(System.IAsyncResult result) {
            Dropthings.DiggSilverlight.DropthingsWebService.SaveWidgetStateResponse retVal = ((Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap)(this)).EndSaveWidgetState(result);
        }
        
        private System.IAsyncResult OnBeginSaveWidgetState(object[] inValues, System.AsyncCallback callback, object asyncState) {
            int widgetId = ((int)(inValues[0]));
            string state = ((string)(inValues[1]));
            return this.BeginSaveWidgetState(widgetId, state, callback, asyncState);
        }
        
        private object[] OnEndSaveWidgetState(System.IAsyncResult result) {
            this.EndSaveWidgetState(result);
            return null;
        }
        
        private void OnSaveWidgetStateCompleted(object state) {
            if ((this.SaveWidgetStateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.SaveWidgetStateCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void SaveWidgetStateAsync(int widgetId, string state) {
            this.SaveWidgetStateAsync(widgetId, state, null);
        }
        
        public void SaveWidgetStateAsync(int widgetId, string state, object userState) {
            if ((this.onBeginSaveWidgetStateDelegate == null)) {
                this.onBeginSaveWidgetStateDelegate = new BeginOperationDelegate(this.OnBeginSaveWidgetState);
            }
            if ((this.onEndSaveWidgetStateDelegate == null)) {
                this.onEndSaveWidgetStateDelegate = new EndOperationDelegate(this.OnEndSaveWidgetState);
            }
            if ((this.onSaveWidgetStateCompletedDelegate == null)) {
                this.onSaveWidgetStateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnSaveWidgetStateCompleted);
            }
            base.InvokeAsync(this.onBeginSaveWidgetStateDelegate, new object[] {
                        widgetId,
                        state}, this.onEndSaveWidgetStateDelegate, this.onSaveWidgetStateCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap CreateChannel() {
            return new WidgetServiceSoapClientChannel(this);
        }
        
        private class WidgetServiceSoapClientChannel : ChannelBase<Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap>, Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap {
            
            public WidgetServiceSoapClientChannel(System.ServiceModel.ClientBase<Dropthings.DiggSilverlight.DropthingsWebService.WidgetServiceSoap> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginAddWidgetInstance(int widgetId, int toZone, int toRow, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = widgetId;
                _args[1] = toZone;
                _args[2] = toRow;
                System.IAsyncResult _result = base.BeginInvoke("AddWidgetInstance", _args, callback, asyncState);
                return _result;
            }
            
            public void EndAddWidgetInstance(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("AddWidgetInstance", _args, result);
            }
            
            public System.IAsyncResult BeginAssignPermission(Dropthings.DiggSilverlight.DropthingsWebService.AssignPermissionRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("AssignPermission", _args, callback, asyncState);
                return _result;
            }
            
            public Dropthings.DiggSilverlight.DropthingsWebService.AssignPermissionResponse EndAssignPermission(System.IAsyncResult result) {
                object[] _args = new object[0];
                Dropthings.DiggSilverlight.DropthingsWebService.AssignPermissionResponse _result = ((Dropthings.DiggSilverlight.DropthingsWebService.AssignPermissionResponse)(base.EndInvoke("AssignPermission", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginChangePageLayout(int newLayout, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = newLayout;
                System.IAsyncResult _result = base.BeginInvoke("ChangePageLayout", _args, callback, asyncState);
                return _result;
            }
            
            public void EndChangePageLayout(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("ChangePageLayout", _args, result);
            }
            
            public System.IAsyncResult BeginChangeWidgetTitle(Dropthings.DiggSilverlight.DropthingsWebService.ChangeWidgetTitleRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("ChangeWidgetTitle", _args, callback, asyncState);
                return _result;
            }
            
            public Dropthings.DiggSilverlight.DropthingsWebService.ChangeWidgetTitleResponse EndChangeWidgetTitle(System.IAsyncResult result) {
                object[] _args = new object[0];
                Dropthings.DiggSilverlight.DropthingsWebService.ChangeWidgetTitleResponse _result = ((Dropthings.DiggSilverlight.DropthingsWebService.ChangeWidgetTitleResponse)(base.EndInvoke("ChangeWidgetTitle", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCollaspeWidgetInstance(Dropthings.DiggSilverlight.DropthingsWebService.CollaspeWidgetInstanceRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("CollaspeWidgetInstance", _args, callback, asyncState);
                return _result;
            }
            
            public Dropthings.DiggSilverlight.DropthingsWebService.CollaspeWidgetInstanceResponse EndCollaspeWidgetInstance(System.IAsyncResult result) {
                object[] _args = new object[0];
                Dropthings.DiggSilverlight.DropthingsWebService.CollaspeWidgetInstanceResponse _result = ((Dropthings.DiggSilverlight.DropthingsWebService.CollaspeWidgetInstanceResponse)(base.EndInvoke("CollaspeWidgetInstance", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginDeleteWidgetInstance(int widgetId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = widgetId;
                System.IAsyncResult _result = base.BeginInvoke("DeleteWidgetInstance", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDeleteWidgetInstance(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DeleteWidgetInstance", _args, result);
            }
            
            public System.IAsyncResult BeginExpandWidgetInstance(Dropthings.DiggSilverlight.DropthingsWebService.ExpandWidgetInstanceRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("ExpandWidgetInstance", _args, callback, asyncState);
                return _result;
            }
            
            public Dropthings.DiggSilverlight.DropthingsWebService.ExpandWidgetInstanceResponse EndExpandWidgetInstance(System.IAsyncResult result) {
                object[] _args = new object[0];
                Dropthings.DiggSilverlight.DropthingsWebService.ExpandWidgetInstanceResponse _result = ((Dropthings.DiggSilverlight.DropthingsWebService.ExpandWidgetInstanceResponse)(base.EndInvoke("ExpandWidgetInstance", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetWidgetState(Dropthings.DiggSilverlight.DropthingsWebService.GetWidgetStateRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("GetWidgetState", _args, callback, asyncState);
                return _result;
            }
            
            public Dropthings.DiggSilverlight.DropthingsWebService.GetWidgetStateResponse EndGetWidgetState(System.IAsyncResult result) {
                object[] _args = new object[0];
                Dropthings.DiggSilverlight.DropthingsWebService.GetWidgetStateResponse _result = ((Dropthings.DiggSilverlight.DropthingsWebService.GetWidgetStateResponse)(base.EndInvoke("GetWidgetState", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginMaximizeWidgetInstance(int widgetId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = widgetId;
                System.IAsyncResult _result = base.BeginInvoke("MaximizeWidgetInstance", _args, callback, asyncState);
                return _result;
            }
            
            public void EndMaximizeWidgetInstance(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("MaximizeWidgetInstance", _args, result);
            }
            
            public System.IAsyncResult BeginMoveWidgetInstance(int instanceId, int toZoneId, int toRow, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = instanceId;
                _args[1] = toZoneId;
                _args[2] = toRow;
                System.IAsyncResult _result = base.BeginInvoke("MoveWidgetInstance", _args, callback, asyncState);
                return _result;
            }
            
            public void EndMoveWidgetInstance(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("MoveWidgetInstance", _args, result);
            }
            
            public System.IAsyncResult BeginResizeWidgetInstance(int widgetId, int width, int height, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = widgetId;
                _args[1] = width;
                _args[2] = height;
                System.IAsyncResult _result = base.BeginInvoke("ResizeWidgetInstance", _args, callback, asyncState);
                return _result;
            }
            
            public void EndResizeWidgetInstance(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("ResizeWidgetInstance", _args, result);
            }
            
            public System.IAsyncResult BeginRestoreWidgetInstance(int widgetId, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = widgetId;
                System.IAsyncResult _result = base.BeginInvoke("RestoreWidgetInstance", _args, callback, asyncState);
                return _result;
            }
            
            public void EndRestoreWidgetInstance(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("RestoreWidgetInstance", _args, result);
            }
            
            public System.IAsyncResult BeginSaveWidgetState(Dropthings.DiggSilverlight.DropthingsWebService.SaveWidgetStateRequest request, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = request;
                System.IAsyncResult _result = base.BeginInvoke("SaveWidgetState", _args, callback, asyncState);
                return _result;
            }
            
            public Dropthings.DiggSilverlight.DropthingsWebService.SaveWidgetStateResponse EndSaveWidgetState(System.IAsyncResult result) {
                object[] _args = new object[0];
                Dropthings.DiggSilverlight.DropthingsWebService.SaveWidgetStateResponse _result = ((Dropthings.DiggSilverlight.DropthingsWebService.SaveWidgetStateResponse)(base.EndInvoke("SaveWidgetState", _args, result)));
                return _result;
            }
        }
    }
}
